# Generated by Django 5.1 on 2024-08-09 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4, 'Username must be at least 4 characters long'), django.core.validators.RegexValidator(message='Username can only contain letters and numbers', regex='^[a-zA-Z0-9]+$')])),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8, 'Password must be at least 8 characters long'), django.core.validators.RegexValidator(message='Password must contain at least one uppercase letter, one lowercase letter, and one digit.', regex='^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)[A-Za-z\\d]*$')])),
            ],
        ),
    ]
