# Generated by Django 5.1 on 2024-08-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignIn',
            new_name='check',
        ),
    ]
