# Generated by Django 5.1 on 2024-08-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_rename_signin_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='password',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='check',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
