# Generated by Django 5.1 on 2024-08-10 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_alter_check_password_alter_check_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Password must contain at least one uppercase letter, one lowercase letter, and one digit.', regex='^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)[A-Za-z\\d]*$')]),
        ),
        migrations.AlterField(
            model_name='check',
            name='username',
            field=models.CharField(error_messages={'unique': 'This username is already taken. Please choose another.'}, max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(4, 'Username must be at least 4 characters long.'), django.core.validators.RegexValidator(message='Username can only contain letters and numbers.', regex='^[A-Za-z\\d]+$')]),
        ),
    ]
