# Generated by Django 5.1 on 2024-08-10 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_alter_check_password_alter_check_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='check',
            new_name='User',
        ),
    ]
