# Generated by Django 5.1 on 2024-08-10 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_rename_check_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
